# Benchmarks

## Initialize

In [1]:
import os
import math
import pathlib
import numpy as np
import pandas as pd
import pyarrow as pa
import pyarrow.feather as feather
from tqdm.auto import tqdm
from IPython.display import clear_output

import warnings
from lifelines.utils import CensoringType
from lifelines.utils import concordance_index

In [2]:
node = !hostname
if "sc" in node[0]:
    base_path = "/sc-projects/sc-proj-ukb-cvd"
else: 
    base_path = "/data/analysis/ag-reils/ag-reils-shared/cardioRS"
print(base_path)

project_label = "22_medical_records"
project_path = f"{base_path}/results/projects/{project_label}"
figure_path = f"{project_path}/figures"
output_path = f"{project_path}/data"

pathlib.Path(figure_path).mkdir(parents=True, exist_ok=True)
pathlib.Path(output_path).mkdir(parents=True, exist_ok=True)

experiment = 230425
experiment_path = f"{output_path}/{experiment}"
pathlib.Path(experiment_path).mkdir(parents=True, exist_ok=True)

/sc-projects/sc-proj-ukb-cvd

In [3]:
endpoints_md = pd.read_csv(f"{experiment_path}/endpoints.csv")
endpoints = sorted(endpoints_md.endpoint.to_list())

In [4]:
baseline_covariates = pd.read_feather('/sc-projects/sc-proj-ukb-cvd/data/2_datasets_pre/230424_medicalhistory/baseline_covariates.feather').set_index("eid")

In [5]:
baseline_records = pd.read_feather('/sc-projects/sc-proj-ukb-cvd/results/projects/22_medical_records/data/baseline_outcomes_220627.feather').set_index("eid")

In [6]:
data_baseline = baseline_covariates.merge(baseline_records, left_index=True, right_index=True, how="left")

In [7]:
data_baseline[[c for c in data_baseline.columns if "fh" in c]]

,fh_alzheimer's_disease/dementia_0_0,fh_bowel_cancer_0_0,fh_breast_cancer_0_0,fh_chronic_bronchitis/emphysema_0_0,fh_diabetes_0_0,fh_heart_disease_0_0,fh_high_blood_pressure_0_0,fh_lung_cancer_0_0,fh_parkinson's_disease_0_0,fh_severe_depression_0_0,fh_stroke_0_0
eid,,,,,,,,,,,
1000018,False,False,False,False,False,False,True,True,False,False,False
1000020,True,False,False,False,False,False,False,False,False,False,False
1000037,False,True,False,False,False,False,True,False,False,False,False
1000043,False,False,False,False,False,False,False,True,False,False,False
1000051,True,False,False,False,True,False,True,False,False,False,True
...,...,...,...,...,...,...,...,...,...,...,...
6025150,False,False,False,True,False,True,True,False,False,False,False
6025165,False,False,False,True,False,True,True,False,False,False,False
6025173,False,False,False,False,True,True,False,False,False,False,True
6025182,False,False,False,False,False,False,False,False,False,False,False
6025198,False,False,False,False,False,False,False,False,False,False,False

In [8]:
endpoints_md[endpoints_md.phecode_string.str.contains("erectile")]

,Unnamed: 0,endpoint,eligable,n,freq,phecode,phecode_string,phecode_category,sex,ICD10_only,phecode_top,leaf
1416,1416,phecode_605-1,209847,25611,0.122046,605.1,Male erectile dysfunction,Genitourinary,Male,0.0,605.0,1.0

In [9]:
endpoints_md[endpoints_md.phecode==705.1]

,Unnamed: 0,endpoint,eligable,n,freq,phecode,phecode_string,phecode_category,sex,ICD10_only,phecode_top,leaf
1622,1622,phecode_705-1,497765,7445,0.014957,705.1,Rheumatoid arthritis,Musc/Skel,Both,0.0,705.0,0.0

In [10]:
# process for downstream cox models

In [11]:
covariate_map = {
    'ATC_C02_antihypertensives_0_0': "antihypertensives",
    'ATC_H02_corticosteroids_for_systemic_use_0_0': "corticosteroids",
    'ATC_N05_psycholeptics_0_0': "psycholeptics",
    'age_at_recruitment_f21022_0_0': "age",
    'cholesterol_f30690_0_0': "cholesterol",
    'ethnic_background_f21000_0_0': "ethnic_background",
    'fh_heart_disease_0_0': "fh_heart_disease",
    'hdl_cholesterol_f30760_0_0': "hdl_cholesterol",
    'phecode_202-1_prev': "diabetes1",
    'phecode_202-2_prev': "diabetes2",
    'phecode_202_prev': "diabetes",
    'phecode_286-1_prev': "bipolar_disorder",
    'phecode_286-2_prev': "major_depressive_disorder",
    'phecode_287-1_prev': "schizophrenia",
    'phecode_331-6_prev': "migraine",
    'phecode_416-21_prev': "atrial_fibrillation",
    'phecode_584_prev': "renal_failure",
    'phecode_605-1_prev': "male_erectile_dysfunction",
    'phecode_700-11_prev': "systemic_lupus_erythematosus",
    'phecode_705-1_prev': "rheumatoid_arthritis",
    'sex_f31_0_0': "sex",
    'smoking_status_f20116_0_0': "smoking_status",
    'standing_height_f50_0_0': "height",
    'systolic_blood_pressure_automated_reading_f4080_0_0': "systolic_blood_pressure_0",
    'systolic_blood_pressure_automated_reading_f4080_0_1': "systolic_blood_pressure_1",
    'weight_f21002_0_0': "weight",
    
        # comorbidities
    'phecode_057-1_prev': 'aids',
  'phecode_121_prev': 'leukemia',
  'phecode_122_prev': 'lymphoma',
  'phecode_130_prev': 'solid_tumor',
  'phecode_202_prev': 'diabetes',
  'phecode_328_prev': 'dementia',
    "phecode_436_prev": "atherosclerosis",
  'phecode_341-2_prev': 'hemiplegia',
    "phecode_401_prev": "hypertension",
  'phecode_404-1_prev': 'myocardial_infarction',
  'phecode_424_prev': 'heart_failure',
  'phecode_431_prev': 'stroke_tia',
  'phecode_448_prev': 'pad',
  'phecode_474_prev': 'copd',
  'phecode_513_prev': 'peptic_ulcer',
  'phecode_542_prev': 'chronic_liver_disease',
  'phecode_583_prev': 'chronic_kidney_disease',
    "phecode_557_prev": "gi_hemorrhage",
  'phecode_700_prev': 'connective_tissue_disorder',
}

In [12]:
data_covariates_pre = data_baseline[covariate_map]
data_covariates_pre.columns = [covariate_map[c] for c in data_covariates_pre.columns]

/tmp/ipykernel_2203721/3792960407.py:1: FutureWarning: Passing a dict as an indexer is deprecated and will raise in a future version. Use a list instead.
  data_covariates_pre = data_baseline[covariate_map]

In [13]:
# prepare new variables
data_covariates = data_covariates_pre.copy()
data_covariates["age"] = data_covariates["age"].astype(np.int32)
data_covariates["bmi"] = data_covariates["weight"] / (data_covariates["height"]/100)**2
data_covariates["systolic_blood_pressure"] = pd.concat([data_covariates["systolic_blood_pressure_0"], data_covariates["systolic_blood_pressure_1"]], axis=1).agg(np.mean, 1)

ethn_bg_def = {"White": ["White", "British", "Irish", "Any other white background"],
                "Mixed": ["Mixed", "White and Black Caribbean", "White and Black African", "White and Asian", "Any other mixed background"],  
                "Asian": ["Asian or Asian British", "Indian", "Pakistani", "Bangladeshi", "Any other Asian background"], 
                "Black": ["Black or Black British", "Caribbean", "African", "Any other Black background"],
                "Chinese": ["Chinese"],  
                np.nan: ["Other ethnic group", "Do not know", "Prefer not to answer"]}

ethn_bg_dict = {}
for key, values in ethn_bg_def.items(): 
    for value in values:
        ethn_bg_dict[value]=key 
        
data_covariates["ethnic_background"].replace(ethn_bg_dict, inplace=True)
data_covariates["ethnic_background"] = data_covariates["ethnic_background"].astype("category")

In [14]:
AgeSex = ["age", "sex"]

SCORE2 = [
    "age", 
    "sex",
    "smoking_status", # current smoker
    "systolic_blood_pressure",
    "cholesterol",
    "hdl_cholesterol",

] 

ASCVD = [
    "age", 
    "sex",
    "ethnic_background",
    "smoking_status", # current smoker
    "diabetes", # diabetes
    "antihypertensives", 
    "systolic_blood_pressure",
    "cholesterol",
    "hdl_cholesterol",
] 

QRISK3 = [
    "age", 
    "sex",
    "ethnic_background",
    "smoking_status", # current smoker
    "bmi",
    "diabetes1", # type 1 diabetes
    "diabetes2", # type 1 diabetes
    "fh_heart_disease",
    "renal_failure", # renal failure
    "atrial_fibrillation", # Atrial Fibrillation
    "migraine", # Migraine
    "rheumatoid_arthritis", # Rheumatoid Arthritis
    "systemic_lupus_erythematosus", # SLE
    "schizophrenia", # Schizophrenia
    "bipolar_disorder", # Bipolar disorder
    "major_depressive_disorder", # Major depressive disorder
    "male_erectile_dysfunction", # Male Erectile dysfunction
    "antihypertensives", 
    "corticosteroids",
    "psycholeptics",
    "systolic_blood_pressure",
    "cholesterol",
    "hdl_cholesterol",
]

Comorbidities = [
    'aids',
    'leukemia',
    'lymphoma',
    'solid_tumor',
    'diabetes',
    'dementia',
    'hemiplegia',
    'myocardial_infarction',
    'heart_failure',
    'stroke_tia',
    'pad',
    'copd',
    'peptic_ulcer',
    'chronic_liver_disease',
    'chronic_kidney_disease', 
    'connective_tissue_disorder'
]

# assert, that all variables are available
covariates_scores = sorted(list(set(AgeSex + SCORE2 + ASCVD + QRISK3 + Comorbidities)))
if not set(covariates_scores).issubset(data_covariates.columns.to_list()):
    print("Not all required covariates are prepared!", list(set(covariates_scores).difference(data_covariates.columns.to_list())))
else:
    print("Success, all required covariates are prepared!")
    data_covariates = data_covariates[covariates_scores]

Success, all required covariates are prepared!

In [15]:
# prepare as float32
data_covariates[data_covariates.select_dtypes(np.float64).columns] = data_covariates.select_dtypes(np.float64).astype(np.float32)

In [16]:
data_covariates

,age,aids,antihypertensives,atrial_fibrillation,bipolar_disorder,bmi,cholesterol,chronic_kidney_disease,chronic_liver_disease,connective_tissue_disorder,...,psycholeptics,renal_failure,rheumatoid_arthritis,schizophrenia,sex,smoking_status,solid_tumor,stroke_tia,systemic_lupus_erythematosus,systolic_blood_pressure
eid,,,,,,,,,,,,,,,,,,,,,
1000018,49,False,False,False,False,26.555672,5.255,False,False,False,...,False,False,False,False,Female,Current,False,False,False,159.5
1000020,59,False,False,False,False,22.746511,7.372,False,False,False,...,False,False,False,False,Male,Current,False,False,False,133.0
1000037,59,False,False,False,False,32.421104,NaN,False,False,False,...,False,False,False,False,Female,Previous,False,False,False,118.5
1000043,63,False,False,False,False,29.567902,5.089,False,False,False,...,False,False,False,False,Male,Previous,True,False,False,141.5
1000051,51,False,False,False,False,41.022221,NaN,False,False,False,...,True,False,False,False,Female,Never,False,False,False,117.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6025150,43,False,False,False,False,25.349253,5.775,False,False,False,...,False,False,False,False,Female,Never,False,False,False,122.5
6025165,45,False,False,False,False,24.227461,5.631,False,False,False,...,False,False,False,False,Female,Never,False,False,False,152.5
6025173,57,False,False,False,False,25.950397,5.583,False,False,False,...,False,False,False,False,Male,Never,False,False,False,131.0
6025182,56,False,False,False,False,29.142521,6.224,False,False,False,...,False,False,False,False,Male,Previous,False,False,False,127.5
6025198,67,False,False,False,False,29.598797,7.049,False,False,False,...,False,False,False,False,Male,Current,False,False,False,156.5

In [17]:
data_covariates.reset_index().to_feather(f"{experiment_path}/data_covariates_full.feather")

In [18]:
data_covariates.dtypes

age                                int32
aids                                bool
antihypertensives                   bool
atrial_fibrillation                 bool
bipolar_disorder                    bool
bmi                              float32
cholesterol                      float32
chronic_kidney_disease              bool
chronic_liver_disease               bool
connective_tissue_disorder          bool
copd                                bool
corticosteroids                     bool
dementia                            bool
diabetes                            bool
diabetes1                           bool
diabetes2                           bool
ethnic_background               category
fh_heart_disease                    bool
hdl_cholesterol                  float32
heart_failure                       bool
hemiplegia                          bool
leukemia                            bool
lymphoma                            bool
major_depressive_disorder           bool
male_erectile_dysfunction           bool
migraine                            bool
myocardial_infarction               bool
pad                                 bool
peptic_ulcer                        bool
psycholeptics                       bool
renal_failure                       bool
rheumatoid_arthritis                bool
schizophrenia                       bool
sex                             category
smoking_status                  category
solid_tumor                         bool
stroke_tia                          bool
systemic_lupus_erythematosus        bool
systolic_blood_pressure          float32
dtype: object

In [19]:
data_covariates.isna().sum(axis=0)

age                                 0
aids                                0
antihypertensives                   0
atrial_fibrillation                 0
bipolar_disorder                    0
bmi                              3104
cholesterol                     32911
chronic_kidney_disease              0
chronic_liver_disease               0
connective_tissue_disorder          0
copd                                0
corticosteroids                     0
dementia                            0
diabetes                            0
diabetes1                           0
diabetes2                           0
ethnic_background                7334
fh_heart_disease                    0
hdl_cholesterol                 72626
heart_failure                       0
hemiplegia                          0
leukemia                            0
lymphoma                            0
major_depressive_disorder           0
male_erectile_dysfunction           0
migraine                            0
myocardial_infarction               0
pad                                 0
peptic_ulcer                        0
psycholeptics                       0
renal_failure                       0
rheumatoid_arthritis                0
schizophrenia                       0
sex                                 0
smoking_status                   2948
solid_tumor                         0
stroke_tia                          0
systemic_lupus_erythematosus        0
systolic_blood_pressure         30115
dtype: int64

In [20]:
data_covariates.describe(include="all")

,age,aids,antihypertensives,atrial_fibrillation,bipolar_disorder,bmi,cholesterol,chronic_kidney_disease,chronic_liver_disease,connective_tissue_disorder,...,psycholeptics,renal_failure,rheumatoid_arthritis,schizophrenia,sex,smoking_status,solid_tumor,stroke_tia,systemic_lupus_erythematosus,systolic_blood_pressure
count,502460.000000,502460,502460,502460,502460,499356.000000,469549.000000,502460,502460,502460,...,502460,502460,502460,502460,502460,499512,502460,502460,502460,472345.000000
unique,NaN,2,2,2,2,NaN,NaN,2,2,2,...,2,2,2,2,2,3,2,2,2,NaN
top,NaN,False,False,False,False,NaN,NaN,False,False,False,...,False,False,False,False,Female,Never,False,False,False,NaN
freq,NaN,502026,494993,497277,501038,NaN,NaN,489872,498495,499998,...,493578,500273,497765,501435,273353,273497,467151,494276,501875,NaN
mean,56.528924,NaN,NaN,NaN,NaN,27.432650,5.692414,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,137.822464
std,8.095128,NaN,NaN,NaN,NaN,4.802981,1.144947,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,18.679060
min,37.000000,NaN,NaN,NaN,NaN,12.121212,0.601000,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,65.000000
25%,50.000000,NaN,NaN,NaN,NaN,24.138910,4.906000,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,124.500000
50%,58.000000,NaN,NaN,NaN,NaN,26.743271,5.650000,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,136.000000
75%,63.000000,NaN,NaN,NaN,NaN,29.908392,6.424000,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,149.500000
max,73.000000,NaN,NaN,NaN,NaN,74.683739,15.460000,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,268.000000